spring.application.name=gamedev-api
gemini.api.base-url=https://generativelanguage.googleapis.com
gemini.api.key=${GEMINI_API_KEY}
gemini.api.model=gemini-3.6-flash
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=11MB
